Grupo No 2 Cuentas por Pagar/Fase IV Construccion/CuentasPorPagar/CuentasPorPagar/Controllers/TipoDocController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CuentasPorPagar.Models;

namespace CuentasPorPagar.Controllers
{
    public class TipoDocController : Controller
    {
        private UsersContext db = new UsersContext();

        //
        // GET: /TipoDoc/

        public ActionResult Index()
        {
            return View(db.tipoDocumentoes.ToList());
        }

        //
        // GET: /TipoDoc/Details/5

        public ActionResult Details(int id = 0)
        {
            tipoDocumento tipodocumento = db.tipoDocumentoes.Find(id);
            if (tipodocumento == null)
            {
                return HttpNotFound();
            }
            return View(tipodocumento);
        }

        //
        // GET: /TipoDoc/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /TipoDoc/Create

        [HttpPost]
        public ActionResult Create(tipoDocumento tipodocumento)
        {
            if (ModelState.IsValid)
            {
                db.tipoDocumentoes.Add(tipodocumento);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tipodocumento);
        }

        //
        // GET: /TipoDoc/Edit/5

        public ActionResult Edit(int id = 0)
        {
            tipoDocumento tipodocumento = db.tipoDocumentoes.Find(id);
            if (tipodocumento == null)
            {
                return HttpNotFound();
            }
            return View(tipodocumento);
        }

        //
        // POST: /TipoDoc/Edit/5

        [HttpPost]
        public ActionResult Edit(tipoDocumento tipodocumento)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tipodocumento).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tipodocumento);
        }

        //
        // GET: /TipoDoc/Delete/5

        public ActionResult Delete(int id = 0)
        {
            tipoDocumento tipodocumento = db.tipoDocumentoes.Find(id);
            if (tipodocumento == null)
            {
                return HttpNotFound();
            }
            return View(tipodocumento);
        }

        //
        // POST: /TipoDoc/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            tipoDocumento tipodocumento = db.tipoDocumentoes.Find(id);
            db.tipoDocumentoes.Remove(tipodocumento);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Grupo No 2 Cuentas por Pagar/Fase IV Construccion/CuentasPorPagar/CuentasPorPagar/Views/TipoDoc/Create.cshtml
@model CuentasPorPagar.Models.tipoDocumento

@{
    ViewBag.Title = "Create";
}

<h2>Nuevo tipo de documento</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Tipo de Documento</legend>

 

        <div class="editor-label">
            Nombre
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.nombre)
            @Html.ValidationMessageFor(model => model.nombre)
        </div>

        <p>
            <input type="submit" value="Guardar" class="btn btn-success" />
        </p>
    </fieldset>
}

<div>
  <a href="@Url.Action("Index","TipoDoc")" class="btn btn-primary" >Regresar a la Lista</a>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Grupo No 2 Cuentas por Pagar/Fase IV Construccion/CuentasPorPagar/CuentasPorPagar/Views/TipoDoc/Delete.cshtml
@model CuentasPorPagar.Models.tipoDocumento

@{
    ViewBag.Title = "Delete";
}


<h2>Confirmacion de Eliminacion</h2>
<fieldset>
    <legend>¿Seguro que desea eliminar el siguiente tipo de Documento?</legend>

      <table class="table table-striped span3">
          <tr>
              <td>
                Id del Tipo de Documento
              </td>
              <td>
                @Html.DisplayFor(model => model.idTipoDocumento)
              </td>
          </tr>
           <tr>
              <td>
                Nombre
              </td>
              <td>
                 @Html.DisplayFor(model => model.nombre)
              </td>
          </tr>
      </table>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Eliminar" class="btn btn-primary"/> |
         <a href="@Url.Action("Index","TipoDoc")" class="btn btn-success">Regresar a la lista</a>
    </p>
}

Grupo No 2 Cuentas por Pagar/Fase IV Construccion/CuentasPorPagar/CuentasPorPagar/Views/TipoDoc/Details.cshtml
@model CuentasPorPagar.Models.tipoDocumento

@{
    ViewBag.Title = "Details";
}

<h2>Detalle del Tipo de Documento</h2>

<fieldset>
    <legend>Tipo de Documento</legend>
      <table class="table table-striped span3">
          <tr>
              <td>
                Id del Tipo de Documento
              </td>
              <td>
                @Html.DisplayFor(model => model.idTipoDocumento)
              </td>
          </tr>
           <tr>
              <td>
                Nombre
              </td>
              <td>
                 @Html.DisplayFor(model => model.nombre)
              </td>
          </tr>
      </table>

</fieldset>
<p>
     <a href="@Url.Action("Edit", "TipoDoc", new { id=Model.idTipoDocumento })" class="btn btn-primary">Editar </a>
     |
    <a href="@Url.Action("Index","TipoDoc")" class="btn btn-primary" >Regresar a la Lista</a>
</p>

Grupo No 2 Cuentas por Pagar/Fase IV Construccion/CuentasPorPagar/CuentasPorPagar/Views/TipoDoc/Edit.cshtml
@model CuentasPorPagar.Models.tipoDocumento

@{
    ViewBag.Title = "Edit";
}

<h2>Editar Tipo de Documento </h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Tipo de Documento</legend>

        <div class="editor-label">
           Id del Tipo de Documento
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.idTipoDocumento, new { @readonly = "readonly", @class="input-small"})
            @Html.ValidationMessageFor(model => model.idTipoDocumento)
        </div>

        <div class="editor-label">
           Nombre
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.nombre)
            @Html.ValidationMessageFor(model => model.nombre)
        </div>

        <p>
            <input type="submit" class="btn btn-primary" value="Guardar" />
        </p>
    </fieldset>
}

<div>
    <a href="@Url.Action("Index","TipoDoc")" class="btn btn-success">Regresar a la lista</a>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Grupo No 2 Cuentas por Pagar/Fase IV Construccion/CuentasPorPagar/CuentasPorPagar/Views/TipoDoc/Index.cshtml
@model IEnumerable<CuentasPorPagar.Models.tipoDocumento>

@{
    ViewBag.Title = "Index";
}

<h2>Tipos de Documentos</h2>

<p>
    <a href="@Url.Action("Create","TipoDoc")" class="btn btn-primary">Nuevo Documento</a>
</p>
<table class="table table-striped">
    <tr>
        <th>
           Id del Tipo de  Documento
        </th>
        <th>
           Descripcion
        </th>
        <th>
            Acciones
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.idTipoDocumento)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.nombre)
        </td>
        <td>
                 <div class="btn-group">
                    <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
                        Acción
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                     
                            <li>@Html.ActionLink("Editar", "Edit", new { id=item.idTipoDocumento  })</li>
                            <li> @Html.ActionLink("Ver", "Details", new { id=item.idTipoDocumento  })</li>
                            <li class="divider"></li>
                            <li>@Html.ActionLink("Eliminar", "Delete", new { id=item.idTipoDocumento  })</li>
                               
               
                    </ul>
                </div>

        </td>
    </tr>
}

</table>