Grupo No 7 Activo Fijo/Fase IV Construccion/MvcActivoFijo/MvcActivoFijo/Controllers/ExampleLayoutsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BootstrapMvcSample.Controllers
{
    public class ExampleLayoutsController : Controller
    {
        public ActionResult Starter()
        {
            return View();
        }

        public ActionResult Marketing()
        {
            return View();
        }

        public ActionResult Fluid()
        {
            return View();
        }

        public ActionResult Narrow()
        {
            return View();
        }

        public ActionResult SignIn()
        {
            return View();
        }

        public ActionResult Contact()
        {
            return View();
        }

        public ActionResult About()
        {
            return View();
        }

        public ActionResult StickyFooter()
        {
            return View("TBD");
        }

        public ActionResult Carousel()
        {
            return View("TBD");
        }
    }
}

Grupo No 7 Activo Fijo/Fase IV Construccion/MvcActivoFijo/MvcActivoFijo/Views/ExampleLayouts/About.cshtml
@model dynamic

@{
    ViewBag.Title = "Acerca De";
    Layout = "~/Views/shared/_BootstrapLayout.basic.cshtml";
}

<hgroup class="title">
    <h1>@ViewBag.Title</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<article>
    <p>
        
    </p>

    <h3><b>
        Equipo de desarrollo Developer Team UCA 2013.
    </b></h3>

    <p>
        --> Ronnie Rios
    </p>
    <p>
        --> Carlos Berroteran
    </p>
</article>

<aside>
    <h3>Sistema de control de Activos Fijos</h3>
    <p>
        Modulo de un sistema ERP elaborado por el grupo de ISTI IV UCA.
    </p>
    <ul>
        <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
  @*      <li>@Html.ActionLink("Acerca de", "../ExampleLayouts/About", "ExampleLayouts")</li>
        <li>@Html.ActionLink("Contacto", "../ExampleLayouts/Contact", "ExampleLayouts")</li>*@
    </ul>
</aside>

Grupo No 7 Activo Fijo/Fase IV Construccion/MvcActivoFijo/MvcActivoFijo/Views/ExampleLayouts/Contact.cshtml
@{
    ViewBag.Title = "Contacto";
}

<hgroup class="title">
    <h1>@ViewBag.Title</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<section class="contact">
    <header>
        <h3>Teléfono</h3>
    </header>
    <p>
        <span class="label">Principal:</span>
        <span>(505) 2233-5678</span>
    </p>
    <p>
        <span class="label">Fuera del horario laboral:</span>
        <span>(505) 2233-5566</span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Correo electrónico</h3>
    </header>
    <p>
        <span class="label">Gerencia:</span>
        <span><a href="mailto:Support@example.com">gerencia@develperteamUCA.com</a></span>
    </p>
    <p>
        <span class="label">Recursos Humanos:</span>
        <span><a href="mailto:Marketing@example.com">recursoshumanos@develperteamUCA.com</a></span>
    </p>
    <p>
        <span class="label">Servicios:</span>
        <span><a href="mailto:General@example.com">servicios@develperteamUCA.com</a></span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Dirección</h3>
    </header>
    <p>
        Unversidad Centroamericana (UCA)<br />
        Rotonda Rubén Darío 150 mts. al oeste.<br />
        Managua, Nicaragua
    </p>

        <ul>
        <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
  @*      <li>@Html.ActionLink("Acerca de", "../ExampleLayouts/About", "ExampleLayouts")</li>
        <li>@Html.ActionLink("Contacto", "../ExampleLayouts/Contact", "ExampleLayouts")</li>*@
    </ul>
</section>

Grupo No 7 Activo Fijo/Fase IV Construccion/MvcActivoFijo/MvcActivoFijo/Views/ExampleLayouts/Fluid.cshtml
@model dynamic

@{
    ViewBag.Title = "title";
    Layout = "~/Views/shared/_BootstrapLayout.basic.cshtml";
}

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li class="active"><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li class="nav-header">Sidebar</li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li class="nav-header">Sidebar</li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <div class="hero-unit">
            <h1>Hello, world!</h1>
            <p>This is a template for a simple marketing or informational website. It includes a large callout called the hero unit and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
            <p><a class="btn btn-primary btn-large">Learn more &raquo;</a></p>
          </div>
          <div class="row-fluid">
            <div class="span4">
              <h2>Heading</h2>
              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
              <p><a class="btn" href="#">View details &raquo;</a></p>
            </div><!--/span-->
            <div class="span4">
              <h2>Heading</h2>
              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
              <p><a class="btn" href="#">View details &raquo;</a></p>
            </div><!--/span-->
            <div class="span4">
              <h2>Heading</h2>
              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
              <p><a class="btn" href="#">View details &raquo;</a></p>
            </div><!--/span-->
          </div><!--/row-->
          <div class="row-fluid">
            <div class="span4">
              <h2>Heading</h2>
              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
              <p><a class="btn" href="#">View details &raquo;</a></p>
            </div><!--/span-->
            <div class="span4">
              <h2>Heading</h2>
              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
              <p><a class="btn" href="#">View details &raquo;</a></p>
            </div><!--/span-->
            <div class="span4">
              <h2>Heading</h2>
              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
              <p><a class="btn" href="#">View details &raquo;</a></p>
            </div><!--/span-->
          </div><!--/row-->
        </div><!--/span-->
      </div><!--/row-->

Grupo No 7 Activo Fijo/Fase IV Construccion/MvcActivoFijo/MvcActivoFijo/Views/ExampleLayouts/Marketing.cshtml
@model dynamic

@{
    ViewBag.Title = "title";
    Layout = "~/Views/shared/_BootstrapLayout.basic.cshtml";
}

     <!-- Main hero unit for a primary marketing message or call to action -->
      <div class="hero-unit">
        <h1>Control para Activo Fijo</h1>
        <p style="text-align: justify;">Este es un modulo para el manejo y control de los activos fijos de una organizacion. Es una parte de un sistema ERP integrado que contiene una serie de catalogos para el almacenamiento de los datos persitentes asi como un seccion de movimientos para la administracion de los acivos fijos.</p>
        <p><a class="btn btn-primary btn-large">Iniciar Sesion &raquo;</a></p>
      </div>

      <!-- Example row of columns -->
      <div class="row">
        <div class="span4">
          <h2>Acerca De</h2>
          <p  style="text-align: justify;">El equipo de desarrollo fueron dos estudiantes de ingenieria en sistemas de la Universidad Centroamericana, quienes trabajaron en este modulo de Activo Fijo para el sistema ERP.</p>
          <p><a class="btn" href="#">Ver Mas &raquo;</a></p>
        </div>
        <div class="span4">
          <h2>Contacto</h2>
          <p style="text-align: justify;">En esta seccion encontraras la informacion necesaria para contactar al equipo de desarrollo.</p>
          <p><a class="btn" href="#">Ver Mas &raquo;</a></p>
       </div>
        <div class="span4">
          <h2>Otros Modulos</h2>
          <p style="text-align: justify;">En esta seccion econtraras los demas modulos que conforman en su cojunto el sistema ERP desarrollado por el grupo de ISTI IV de la UCA.</p>
          <p><a class="btn" href="#">Ver Mas &raquo;</a></p>
        </div>
      </div>

Grupo No 7 Activo Fijo/Fase IV Construccion/MvcActivoFijo/MvcActivoFijo/Views/ExampleLayouts/Narrow.cshtml
@model dynamic

@{
    ViewBag.Title = "title";
    Layout = "~/Views/shared/_BootstrapLayout.narrow.cshtml";
}

      <div class="jumbotron">
        <h1>Super awesome marketing speak!</h1>
        <p class="lead">Cras justo odio, dapibus ac facilisis in, egestas eget quam. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
        <a class="btn btn-large btn-success" href="#">Sign up today</a>
      </div>

      <hr>

      <div class="row-fluid marketing">
        <div class="span6">
          <h4>Subheading</h4>
          <p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.</p>

          <h4>Subheading</h4>
          <p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras mattis consectetur purus sit amet fermentum.</p>

          <h4>Subheading</h4>
          <p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
        </div>

        <div class="span6">
          <h4>Subheading</h4>
          <p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.</p>

          <h4>Subheading</h4>
          <p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras mattis consectetur purus sit amet fermentum.</p>

          <h4>Subheading</h4>
          <p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
        </div>
      </div>

Grupo No 7 Activo Fijo/Fase IV Construccion/MvcActivoFijo/MvcActivoFijo/Views/ExampleLayouts/SignIn.cshtml
@model dynamic

@{
    ViewBag.Title = "title";
    Layout = "~/Views/shared/_BootstrapLayout.empty.cshtml";
}

<a href="/">Inicio</a>
<form class="form-signin">
        <h2 class="form-signin-heading">Activo Fijos</h2>
        <input type="text" class="input-block-level" placeholder="Correo Electronico">
        <input type="password" class="input-block-level" placeholder="Contraseña">
        <label class="checkbox">
          <input type="checkbox" value="remember-me"> Recuerdarme
        </label>
        <button class="btn btn-large btn-primary" type="submit">Iniciar sesion</button>
      </form>

Grupo No 7 Activo Fijo/Fase IV Construccion/MvcActivoFijo/MvcActivoFijo/Views/ExampleLayouts/Starter.cshtml
@model dynamic

@{
    ViewBag.Title = "title";
    Layout = "~/Views/shared/_BootstrapLayout.basic.cshtml";
}

<h1>Bootstrap starter template</h1>
<p>Use this document as a way to quick start any new project.<br> All you get is this message and a barebones HTML document.</p>

Grupo No 7 Activo Fijo/Fase IV Construccion/MvcActivoFijo/MvcActivoFijo/Views/ExampleLayouts/TBD.cshtml
@model dynamic

@{
    ViewBag.Title = "title";
    Layout = "~/Views/shared/_BootstrapLayout.cshtml";
}

<h2>Coming Soon!</h2>